Draft: MP-ECDSA
webb-tools/gadget pull request #37
Opened 2023-11-29 15:26 UTC by tbraun96

Closes #26

2023-11-29 18:25 UTC, drewstone requested changes

2023-11-29 18:25 UTC, drewstone commented on Cargo.toml
> +dkg-runtime-primitives = { git = "https://github.com/webb-tools/dkg-substrate" }
Would prefer you don't bring in any of these crates @tbraun96. You should copy over only what needs to be brought over from there.

2023-11-29 18:45 UTC, drewstone requested changes
Some scaffold looks OK, but generally doesn't seem like the approach you've taken is correct given the new architecture. There is no base DKG anymore and it does not rotate on sessions. The client API from `dkg-substrate` is not being included in Tangle mainnet at all. There will be no best authorities, next best authorities, signature thresholds, etc. Everything should be tied to a job. After receiving job details we should execute keygen or signing protocols. CC @1xstj

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn validator_set(
This isn't exactly relevant anymore. The parties participating in the job are taken directly from the job.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn validator_set(
You can get the active validator set from the session API now or using `subxt`.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn should_execute_new_keygen(
This isn't relevant and will not be included in the runtime of the new system.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_next_dkg_pub_key(
There is no next public key anymore, there is just a Phase 1 Job that indicates completing a DKG w/ specified configuration parameters such as validator participants.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn dkg_pub_key_is_unset(&self, header: &B::Header) -> bool {
This isn't something that will be on Tangle mainnet.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_dkg_pub_key(&self, header: &B::Header) -> (AuthoritySetId, Vec<u8>) {
This isn't something that will be on Tangle mainnet.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_party_index(&self, header: &B::Header) -> Option<u16> {
There will be no best authorities on Tangle Mainnet as is currently implemented by `dkg-substrate`. There is just the job and the participants of the job. The party index for a validator is their index in the job's participants.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_best_authorities(&self, header: &B::Header) -> Vec<(u16, AuthorityId)> {
There will be no best authorities on Tangle Mainnet as is currently implemented by dkg-substrate. There is just the job and the participants of the job. The party index for a validator is their index in the job's participants.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_next_party_index(&self, header: &B::Header) -> Option<u16> {
There is no next set of parties. There will be just a job and its participants.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_next_best_authorities(&self, header: &B::Header) -> Vec<(u16, AuthorityId)> {
There is no next best authorities on Tangle mainnet. Just a job and its configuration parameters.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_signature_threshold(&self, header: &B::Header) -> u16 {
There is no main signature threshold and the client API won't implement this as you have it here.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/client.rs
> +    pub async fn get_next_signature_threshold(&self, header: &B::Header) -> u16 {
There is no next signature threshold and the client API won't implement this as you have it here.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/constants.rs
> +    use dkg_primitives::types::SSID;
Please move any `dkg-primitives` into this repo and create a package for it. Some name ideas
- `tangle-mpc-primitives`
- `tangle-dkg-primitives`
open to other suggestions.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/keyring.rs
> +// Copyright 2022 Webb Technologies Inc.
You can update these license headers to be 2022-2023

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/keyring.rs
> +    use dkg_runtime_primitives::crypto;
Avoid bringing in any `dkg-substrate` packages.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/keystore.rs
> +impl DKGKeystore {
If this is the MpEcdsa keystore we should name it such, I think getting more specific and semantically correct names would be beneficial here.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/protocols/managers/keygen.rs
> +    /// Check to see if we need to run a keygen for session 2, 3, 4, .., etc.
This isn't a thing anymore. If there's confusion here you need to clarify how we can assist.

2023-11-29 18:45 UTC, drewstone commented on protocols/mp-ecdsa/src/protocols/managers/keygen.rs
> +        let authority_set = if let Some((active, queued)) = self.client.validator_set(header).await {
Not how it'll go. This is leading me to believe you're not processing everything about the new architecture properly given all our previous discussions.

2023-12-08 13:36 UTC, shekohex commented on protocols/mp-ecdsa/src/protocols/sign.rs
> +                    bincode2::deserialize(&key).expect("Should deserialize");
This `key` here in the job.key is not the `LocalKey`, Thomas. It is the Public Key of the DKG. The "LocalKey" is, by definition, Local to you, the current validator and never shared, please treat that as a private material. It should only exist in the validator database, encrypted.

2023-12-08 13:43 UTC, shekohex commented on protocols/mp-ecdsa/src/protocols/keygen.rs
> +                key_store.set(additional_params.job_id, local_key).await?;
This LocalKey, you should save the key by the `phase_one.job_id` this one you should use above (see my previous comment)

2023-12-12 02:44 UTC, drewstone commented on protocols/mp-ecdsa/src/util.rs
> +        log::warn!(target: "dkg_gadget", "🕸️  Invalid signature len: {}, expected 65", sig_vec.len());
Don't forget to remove dkg_gadget references.

2023-12-13 12:19 UTC, shekohex commented
Looks good. @tbraun96 lets rename webb-gadget to gadget-common and move the client.rs implementation there. Which will be reusable between all gadgets.

2023-12-13 15:25 UTC, shekohex requested changes
Looks good! Just one comment about std feature, to avoid any conflicts when compiling tangle node/runtime.

2023-12-13 15:25 UTC, shekohex commented on gadget-common/Cargo.toml
> +pallet-jobs-rpc-runtime-api = { workspace = true, default-features = false, features = ["std"] }
Lets make `std` feature in that crate, and only enable `std` for other packages/crates only if we enabled `std`

2023-12-13 15:54 UTC, shekohex approved these changes
LGTM!

2023-12-13 16:34 UTC, merged