[Draft] ZkSaaS Gadget
webb-tools/gadget pull request #48
Opened 2024-01-08 20:31 UTC by tbraun96

2024-01-09 02:02 UTC, drewstone requested changes
LG curious your thoughts in certain places, @shekohex please review as well.

2024-01-09 02:02 UTC, drewstone commented on protocols/zk-saas/src/network/mod.rs
> +    SubstrateGadgetMessage {
What about this warrants a `Substrate` prefix? I want to be very meticulous with things like this. If we don't these prefixes (or maybe generalized ones can be better `BlockchainGadgetMessage`) I'm curious to hear more ideas.

2024-01-09 10:31 UTC, shekohex commented on protocols/zk-saas/src/protocol/mod.rs
> +type E = ark_bn254::Bn254;
we will first need to add that information to the Runtime/on-chain types as a `curve` field [here](https://github.com/webb-tools/tangle/blob/9c6db763a6b5f9c0c81a8bbafeab98898928c4b6/primitives/src/jobs/zksaas.rs#L37) for example.

2024-01-09 10:33 UTC, shekohex commented on protocols/zk-saas/src/protocol/mod.rs
> +                            reason: "Phase one job type not ZkSaaS".to_string(),
Yes, they are sanity checks.

2024-01-09 10:36 UTC, shekohex commented on protocols/zk-saas/src/protocol/mod.rs
> +                let JobType::ZkSaaSPhaseTwo(phase_two) = job.job_type else {
They are not conditionins in per se, more like a refutable pattern matching using [let-else](https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html) and ofc they all boils down to branching.

2024-01-09 10:40 UTC, shekohex requested changes
Looks good so far, waiting to see how the testing setup would look like

2024-01-12 19:16 UTC, drewstone commented on protocols/zk-saas/src/protocol/mod.rs
> +                            reason: "Phase one job type not ZkSaaS".to_string(),
I think they can be removed, and if you think we need it I would suggest that we actually prevent this from happening on-chain. This feels more like an _insanity_ check TBH.

2024-01-12 19:20 UTC, drewstone commented on protocols/zk-saas/src/protocol/mod.rs
> +                let JobType::ZkSaaSPhaseTwo(phase_two) = job.job_type else {
But I'm saying this is not needed. On line 81 we literally match to make sure its a ZkSaaSPhaseTwo
```
if matches!(job.job_type, JobType::ZkSaaSPhaseTwo(..)) {
```

2024-01-12 19:22 UTC, drewstone commented on protocols/zk-saas/src/protocol/mod.rs
> +                let JobType::ZkSaaSPhaseTwo(phase_two) = job.job_type else {
So this error will literally never be thrown

2024-01-12 23:16 UTC, merged